"""
🔒 Agent #9: Lock Generator
Проверяет и генерирует lock-файлы для Python/Node проектов.

Что делает:
1. Находит requirements.txt / pyproject.toml / package.json
2. Проверяет наличие lock-файлов
3. --fix: генерирует requirements.lock (pip freeze) из venv
4. --fix: генерирует package-lock.json (npm install --package-lock-only)

Использование:
    python -m agents.lock_generator           # Показать статус
    python -m agents.lock_generator --fix     # Сгенерировать lock-файлы
    python -m agents.lock_generator --save    # + Markdown отчёт
"""

import subprocess
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
from agents.config import PROJECTS, REPORTS_DIR


def detect_stack(project_path: Path) -> dict:
    """Определяет стек проекта и статус lock-файлов."""
    result = {
        "stack": None,
        "deps_file": None,
        "lock_file": None,
        "has_lock": False,
        "has_venv": False,
        "dep_count": 0,
        "unpinned": [],
    }

    # Python: requirements.txt
    req_txt = project_path / "requirements.txt"
    pyproject = project_path / "pyproject.toml"

    if req_txt.exists():
        result["stack"] = "Python"
        result["deps_file"] = "requirements.txt"
        _parse_requirements(req_txt, result)
    elif pyproject.exists():
        result["stack"] = "Python"
        result["deps_file"] = "pyproject.toml"

    # Python lock files
    for lock_name in ("requirements.lock", "requirements-lock.txt", "poetry.lock", "uv.lock"):
        if (project_path / lock_name).exists():
            result["lock_file"] = lock_name
            result["has_lock"] = True
            break

    # Python venv
    for venv_name in (".venv", "venv"):
        if (project_path / venv_name).is_dir():
            result["has_venv"] = True
            break

    # Node: package.json
    pkg_json = project_path / "package.json"
    if pkg_json.exists():
        if result["stack"] is None:
            result["stack"] = "Node.js"
        else:
            result["stack"] += " + Node.js"
        result["deps_file"] = result["deps_file"] or "package.json"

        # Node lock
        for lock_name in ("package-lock.json", "yarn.lock", "pnpm-lock.yaml", "bun.lockb"):
            if (project_path / lock_name).exists():
                result["lock_file"] = lock_name
                result["has_lock"] = True
                break

    return result


def _parse_requirements(req_path: Path, result: dict):
    """Парсит requirements.txt для подсчёта deps и unpinned."""
    try:
        lines = req_path.read_text(encoding="utf-8").strip().split("\n")
    except OSError:
        return

    for line in lines:
        line = line.strip()
        if not line or line.startswith("#") or line.startswith("-"):
            continue
        result["dep_count"] += 1
        # Unpinned = нет == (есть >= или ~= или ^= или просто имя)
        if "==" not in line:
            pkg_name = line.split(">")[0].split("<")[0].split("~")[0].split("^")[0].split("[")[0].strip()
            result["unpinned"].append(pkg_name)


def fix_python_lock(project_name: str, project_path: Path) -> bool:
    """Генерирует requirements.lock из venv."""
    # Ищем venv python
    for venv_name in (".venv", "venv"):
        venv_python = project_path / venv_name / "Scripts" / "python.exe"
        if not venv_python.exists():
            venv_python = project_path / venv_name / "bin" / "python"
        if venv_python.exists():
            break
    else:
        print(f"  ⚠️ {project_name}: venv не найден, пропускаю")
        return False

    try:
        result = subprocess.run(
            [str(venv_python), "-m", "pip", "freeze"],
            capture_output=True, text=True, timeout=30,
            cwd=str(project_path),
        )
        if result.returncode != 0:
            print(f"  ❌ {project_name}: pip freeze failed: {result.stderr[:100]}")
            return False

        lock_path = project_path / "requirements.lock"
        header = f"# Auto-generated by METAai Lock Generator\n# Date: {datetime.now().isoformat()}\n# Source: {venv_name}/\n\n"
        lock_path.write_text(header + result.stdout, encoding="utf-8")
        print(f"  ✅ {project_name}: requirements.lock ({len(result.stdout.strip().split(chr(10)))} packages)")
        return True

    except subprocess.TimeoutExpired:
        print(f"  ⏱️ {project_name}: pip freeze timeout")
        return False


def fix_node_lock(project_name: str, project_path: Path) -> bool:
    """Генерирует package-lock.json."""
    try:
        result = subprocess.run(
            ["npm", "install", "--package-lock-only"],
            capture_output=True, text=True, timeout=60,
            cwd=str(project_path),
            shell=True,
        )
        if result.returncode == 0:
            print(f"  ✅ {project_name}: package-lock.json сгенерирован")
            return True
        else:
            print(f"  ❌ {project_name}: npm failed: {result.stderr[:100]}")
            return False
    except subprocess.TimeoutExpired:
        print(f"  ⏱️ {project_name}: npm timeout")
        return False


def print_console(scan_results: dict[str, dict]):
    """Красивый вывод в консоль."""
    print("\n" + "=" * 60)
    print("  🔒 LOCK GENERATOR — Phase 3 Agent #9")
    print("=" * 60)

    for project_name, info in scan_results.items():
        if info["stack"] is None:
            print(f"  ⚪ {project_name:12s}  Нет зависимостей")
            continue

        if info["has_lock"]:
            emoji = "🟢"
            lock_str = f"Lock: {info['lock_file']}"
        else:
            emoji = "🔴"
            lock_str = "Lock: ❌ ОТСУТСТВУЕТ"

        venv_str = " | venv ✅" if info["has_venv"] else ""
        unpinned_str = f" | ⚠️ {len(info['unpinned'])} unpinned" if info["unpinned"] else ""

        print(f"  {emoji} {project_name:12s}  {info['stack']} | {lock_str}{venv_str}{unpinned_str}")

    print("=" * 60 + "\n")


def generate_report(scan_results: dict[str, dict]) -> str:
    """Генерирует Markdown отчёт."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        f"# 🔒 Lock Generator Report — {now}",
        "",
        "| Проект | Стек | Lock | Venv | Unpinned |",
        "|--------|------|:----:|:----:|:--------:|",
    ]

    for name, info in scan_results.items():
        if info["stack"] is None:
            lines.append(f"| {name} | — | — | — | — |")
            continue
        lock = f"✅ {info['lock_file']}" if info["has_lock"] else "❌"
        venv = "✅" if info["has_venv"] else "—"
        unpinned = str(len(info["unpinned"])) if info["unpinned"] else "0"
        lines.append(f"| {name} | {info['stack']} | {lock} | {venv} | {unpinned} |")

    return "\n".join(lines)


def main():
    args = sys.argv[1:]
    do_fix = "--fix" in args
    save_md = "--save" in args or "--md" in args

    # Сканируем
    scan_results = {}
    for name, path in PROJECTS.items():
        scan_results[name] = detect_stack(path)

    print_console(scan_results)

    # Авто-фикс
    if do_fix:
        print("🔧 Генерация lock-файлов...\n")
        fixed = 0
        for name, info in scan_results.items():
            if info["has_lock"]:
                continue
            project_path = PROJECTS[name]

            if info["stack"] and "Python" in info["stack"] and info["has_venv"]:
                if fix_python_lock(name, project_path):
                    fixed += 1

            if info["stack"] and "Node" in info["stack"]:
                if fix_node_lock(name, project_path):
                    fixed += 1

        if fixed == 0:
            print("\n  Нечего фиксить — все lock-файлы на месте (или нет venv).")
        else:
            print(f"\n  Сгенерировано: {fixed} lock-файлов")
        print()

    if save_md:
        REPORTS_DIR.mkdir(parents=True, exist_ok=True)
        report = generate_report(scan_results)
        timestamp = datetime.now().strftime("%Y%m%d")
        path = REPORTS_DIR / f"locks_{timestamp}.md"
        path.write_text(report, encoding="utf-8")
        print(f"📄 Сохранено: {path}")


if __name__ == "__main__":
    main()
